jenkinsci/digitalocean-plugin

- pom.xml
The upgrade allows to support  building using the latest JDK version. In addition I think depending on the latest LTS version of jenkins should be fine.
> Upgrade to latest jenkins LTS

- README.md
This information should help future contributors to find an easier entry into contributing for this plugin. In addition it should give all required links into the documentation at one place.
> Provide a more complete github landing page

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
The creation of a droplet fails with wrong symbol in name. only a-z,
A-Z, 0-9 and - are allowed symbols.
> [FIXED JENKINS-26352] Droplets no longer allow _ in id

- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
Fixing a typical apt problem that repositories need to be updated from
time to time since the installation of new packages isn't possible
otherwise.
> [FIXED JENKINS-26732] Fix startup problem if debian image hadn't been updated repositories

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
Makes sure that no surprises can happen by reusing container not made for the build system.
> [FIX JENKINS-27279] Do not reused unused container

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/Slave.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
Finally making multiple DigitalOcean containers from the same cloud as they should behave. This allows to create more than one container and also closing them again.
> [Fix JENKINS-27280] Start multiple DO container at once

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/java/com/dubture/jenkins/digitalocean/Utils.java
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-numExecutors.html
Fix an issue where you couldn't create slaves from an image snapshot, because droplet creation was using name slugs. Switch to image IDs.
Allow the number of executors per slave to be configured.
When checking how many slaves are running, filter droplets by their image name. This avoids counting droplets that are unrelated to Jenkins.
Sort lists of objects for getter UX when configuring slaves.
Some other internal refactoring.
> Create slaves from snapshots. configure num executors, ignore non-slave images

- src/main/java/com/dubture/jenkins/digitalocean/Computer.java
- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
- src/main/java/com/dubture/jenkins/digitalocean/RetentionStrategy.java
- src/main/java/com/dubture/jenkins/digitalocean/Slave.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/Slave/configure-entries.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-initScript.html
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-userData.html
Support for configuring:
* Droplet user data
* Jenkins init script
Add a slave configure-entries.jelly to silence an exception when viewing the node's configuring. It's not great but it's better than nothing.
Check for an SSH connection less aggressively, and wait for the droplet to enter the ACTIVE state before doing so.
Increase default idle time to 60 minutes, since that's the minimum you'll pay for anyway.
> Support user data, init script and more!

- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
Revert SSH connection timeout change as it's causing breaks. I don't know what the root cause is, but someone else saw the same symptoms ("Unexpected termination of channel").
> Revert SSH connection timeout change as it's causing breaks

- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/Slave/configure-entries.jelly
You can create droplets by ID or by slug. Currently the plugin always uses the ID, however DigitalOcean periodically update their standard snapshots, which appears to invalidate the old ID for their images. Change the plugin so that when configuring a droplet, it will use the slug for snapshots, but IDs for backups. Existing configuration is unaffected, because the code will always try to parse the stored imageId String as an Integer.
There is one caveat with this change - users that upgrade must note that if they change their droplet configuration, then they'll need to reset their image ID. Existing configuration will work without updates, since numeric image IDs are still supported for backup images. The flip side is that by using image slugs instead of IDs, you shouldn't get bitten …
> Support both slugs and integers for identifying images

- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
@Slezhuk pointed out that user snapshots have a "snapshot" type but a null slug value. Handle this case by using the numeric ID for such images, and prefixing them with "(Snapshot) " in the list of images when configuring droplets.
Also sort the list of images case-insensitively, so that e.g. "Ubuntu node" doesn't fall after "Ubuntu WordPress".
> Handle user snapshots

- pom.xml
- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
With the plugin using newer version of Digital Ocean API library, it started listing duplicate entries for droplet Regions, Images, SSH keys and other. This was caused by the paging code of the plugin.
This issue was mentioned in https://github.com/jenkinsci/digitalocean-plugin/pull/20#issuecomment-228525141
> Fixed paging issue

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-labellessJobsAllowed.html
Previously, if a Slave Template had any labels set, a job not restricted to build on any node would not trigger creation of a Droplet based on such Slave Template. In fact, only Slave Templates with no labels specified were handling jobs not restricted to any label.
This commit adds an option which allows jobs not restricted to any node to trigger the creation of a Droplet based on a Slave Templates that has labels set.
> Add an option for label-less jobs

- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
returning because a sub-function failed is all nice and dandy, given
the listener logger is ephemeral, not leaving persistent information as
to why the launch failed is getting in the way of debugging.
the only way to figure out what happened after the fact is looking at the
jenkins log it seems.
to enable finding out why launching failed log what went wrong before
returning
> log premature return from computer launching

- pom.xml
- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/Computer.java
- src/main/java/com/dubture/jenkins/digitalocean/Slave.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
the cloud-stats plugin is fairly handy to track cloud availability. for it
to work we'll need to pass a ProvisioningActivity id from the cloud all
the way through to the Computer. Slave and Computer become TrackedItems.
> integrate with cloud-stats

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
- src/main/resources/com/dubture/jenkins/digitalocean/Cloud/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/Cloud/help-connectionRetryWait.html
sleeping for only 10 seconds can quickly exhaust the api rate limit
with a lofty instance cap, or crappy provisioning failing half the time, or
bad response time to creation requests on the DO side (e.g. during
maintenance windows the time-to-droplet can rise by multiple minutes).
to prevent exhausting the rate limit make the retry sleeps configurable
> add cloud level configuration for initial connection retry sleeping

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
- src/main/java/com/dubture/jenkins/digitalocean/ComputerLauncher.java
- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/Cloud/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/Cloud/help-usePrivateNetworking.html
iff the master and the cloud are within the same data center the master can
use the private network address of the slaves rather than their public one.
private traffic doesn't count against transfer limits and is usually also
a tad faster.
> add cloud level configuration for private networking

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
cloud-stats introduced in c9fd09e53fd351eb5102f81b8628e7aa1d83801a track
the errors which caused a failed provisioning attempt allowing to easily
identify what the problem was. but to do that one needs a useful context
message.
so, instead of only logging the error causes log them AND then use them
also as message for the thrown error.
> give errors thrown during provision useful context

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
when creating a new DO cloud doFillSshKeyIdItems will be called initially,
with an empty authToken. attempting to list the sshkeys then will cause
an exception, which not only looks silly and screws up the config page,
it also seems to confuse stapler/jelly over when to reload the model
(most times for me entering an auth key did not actually trigger a reload)
by only filling the sshkey model if we got a !empty key, reloading seems
overall more consistent and adding a new cloud doesn't greet the user with
an ugly unhandled exception error.
(also changed the iter variable name from image to key :O)
> do not attempt to list ssh keys without auth token

- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
DO a while ago introduced special droplet variants without cpu stealing or
with enormous amounts of ram. They are listed along the regular sizes which
makes them hard to spot in the list. As they have different pricing and
resource behavior than regular nodes it makes sense to more clearly
indicate which is which.
> codify the droplet type (regular, high-cpu, high-mem) in the label string

- src/main/resources/com/dubture/jenkins/digitalocean/Cloud/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/config.jelly
use repeatableProperty to render the slave template config.jelly
SlaveTemplate is a describable so we can let repeatableProperty do the
heavy lifting of loading the right config.jelly with the right descriptor
scoping.
Also, move delete button out of the SlaveTemplate config.jelly to
the Cloud's. Defining the button in the describable itself is deprecated.
repeatableProperty can add a handle to re-order repeatables if a header
is defined. as this can be handy to manage a greater number of droplets
to sort them in a more logical/human readable order, set a simple header
to get this feature enabled.
> Repeatable template

- src/main/java/com/dubture/jenkins/digitalocean/Cloud.java
I am actually not sure how this was dealt with in the past, but currently
the Cloud object is unmarshalled from the config.xml if present, which
means new members are null unless the user goes to the global config and
saves it so that they get properly initialized.
To deal with this we are now adding custom unmarshalling for the new
members to get initialized with sane default values.
This prevents nullptr exceptions when loading the new plugin on old configs
> convert old configs to new objects and force sane default values

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
When adding support for tags, I noticed the current value of "Install Monitoring" was not displayed when updating the configuration.
> Fix display of "Install monitoring" setting.

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-tags.html
DigitalOcean has the ability to specify network firewalls which are linked to tags, both for the droplets to apply the firewall to, and for the traffic sources.
To take advantage of that, I needed to tag droplets created by this plugin.
The change introduces a new "tags" field, the values of which are passed into the DigitalOcean API.
> Allow specification of DigitalOcean Droplet tags

- src/main/java/com/dubture/jenkins/digitalocean/DigitalOceanCloud.java
getters need to be public since they get called by jelly render to actually
get the runtime value of the associated entry field.
because getInstanceCap was private the currnet value couldn't be
retrieved and the config view was always initialized to the default value
of 5.
simply make the getter public again.
this broken in some style fixes I did before 0.15.
> fix instanceCap resetting to default value every time you open /configure

- src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/config.jelly
- src/main/resources/com/dubture/jenkins/digitalocean/SlaveTemplate/help-setupPrivateNetworking.html
This option allows one to enable private networking on their slave
regardless of whether or not the master will communicate with it
over the internal network.
This comes in handy for build tasks that will execute on the slaves that
need to communicate to a (static) droplet. For instance, pushing to or
pulling from an internal maven repo.
> Added an option allowing private networking inspite of master/slave communication

- src/main/java/com/dubture/jenkins/digitalocean/DigitalOceanComputerLauncher.java
Fix droplets getting lost during launch and as a result getting not not cleaned-up due to failures in getDroplet().  The problem results in many stale droplets being billed against our account because the jenkins launches them, but never deletes them.
> Retry getDroplet during launch

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
More updates from the archetype
https://github.com/jenkinsci/archetypes/blob/master/common-files/.github/release-drafter.yml
Each time a PR is merged, based on the labels it'll add it to a draft release, which makes it easier to fill out the github release notes on release.
> Add release drafter for easier changelogs

- .mvn/extensions.xml
- .mvn/maven.config
Jenkins incrementals will allow unreleased plugins(prs, branches,etc) to be published to a special repo, which makes it easier to test install via jenkins-plugin-cli and other tooling
> Add support for generating jenkins incrementals

- pom.xml
- src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java
DigitalOcean's size api updated the transfer field from being an integer to a float.
This was submitted to the upstream library - https://github.com/jeevatkm/digitalocean-api-java/pull/123
To unblock people, I've forked the library and released my own fork
> JENKINS-68953 - No longer crash when fetching sizes

- README.md
- src/main/java/com/dubture/jenkins/digitalocean/DigitalOceanCloud.java
- src/test/java/com/dubture/jenkins/digitalocean/ConfigurationAsCodeTest.java
- src/test/resources/com/dubture/jenkins/digitalocean/legacy-pre-credentials.yml
Add back in allowing plaintext ssh keys and do token, but only in casc, not in the ui
Fix example in readme.
> Add tests to confirm the casc example in readme works
